parents: ['3dshapes']

#name: 'test-3dshapes'

training:
    epochs: 100

dataset:
    name: 'byfactor'

#    kwargs:
#        factor: shape
#
#        counts: [0, 0, -1, 0]


info:
    dataset_type: '3dshapes'
