parents: ['n/t/transfer-3ds']

output:
    save_freq: 2000

training:

    step_limit: 100000


dataset:
    _type: 'dataset/concat'

    batch_size: 128
    val_split: 0.1

    datasets:

        factor: shape

        _type: 'list'
        _elements:
          - _type: 'dataset/byfactor'
            _mod: 'resamplable'
            budget: 600
            counts: [-1, 0, 0, 0] # [box, cyl, ball, cap]

          - _type: 'dataset/byfactor'
            counts: [0, 600, 0, 0] # [box, cyl, ball, cap]

info:
    dataset_type: 'box-s1'
