
training:
    step_limit: 150000

dataset:
    _type: 'dataset/concat'

    batch_size: 128
    val_split: 0.1

    name: '_x_'

    datasets:

        factor: shape

        _type: 'list'
        _elements:
          - _type: 'dataset/byfactor'
            _mod: 'resamplable'
            budget: 600
            counts: [-1, -1, -1, 0] # [box, cyl, ball, cap]

          - _type: 'dataset/byfactor'
            counts: [0, 0, 0, 600] # [box, cyl, ball, cap]


info:
    dataset_type: 'nocap2cap'
