#parents: ['n/3dshapes']

dataset:

    name: 'transfer'

    budget: 600

    old2new_ratio: 1

    batch_size: 128

    val_split: 0.1

#    new:
#        _type: 'dataset/byfactor'
#
#        factor: shape
#
#        counts: [0, 100, 0, 0] # [box, cyl, ball, cap]

info:
    dataset_type: 'transfer-3ds'
