parents: ['n/basics']

#name: 'test-3dshapes'

training:
    step_limit: 200000

output:
    print_freq: 250

dataset:
    name: 'atari'

    batch_size: 32

    val_split: 0.1

#    dataroot: /is/ei/fleeb/workspace/local_data/test-data


info:
    dataset_type: 'atari'
