parents: ['dspr']

name: 'test-pycharm'

inline: True

output:
  unique_tests: True

model:
#  _type: wpp


#  gen_types: ['hybrid']

#  rec_noise: 0.2

  gan_wt: 1

#  gen_types: ['gen']

#dataset.kwargs.download = true

#resume = 'test-pycharm_191121-154737'
#
#extend = 7