parents: ['fvae', 'dspr']

name: 'test-pycharm'

inline: True

#output:
#  unique_tests: True

#training:
#  max_iter: 101

#model:
#  _type: wpp

#  gan_wt: 1

#  latent_reg_wt: 100

#optim:
#  lr: 2.e-4



#  gen_types: ['gen']

#  rec_noise: 0.2

#  gan_wt: 1

#  gen_types: ['gen']

#dataset.kwargs.download = true

#resume = 'test-pycharm_191121-154737'
#
#extend = 7