
#parents: ['wae', 'large-double', 'atari']

#parents: ['fdwae', 'adain-dec', 'noisy-3dshapes']
#parents: ['n/ae', 'n/double', 'n/3dshapes']

#parents: ['celeba']

parents: ['n/t/box-s2']

#parents: ['vae', 'double', '3dshapes']

#resume: 3dshapes-fwae_0102-5966133-02_200109-133116

#load: box-s1-wae_0047-6049598-02_200201-050901

#game: pacman

#device: cpu
seed: 0

#legacy: True
#
#
##name: 'test-pycharm'
#
inline: True
#
dataset:
  device: cpu
#  batch_size: 4

output:
  print_freq: 50
##  unique_tests: True
#  save_freq: 60
##
#training:
#  val_freq: 60
#  step_limit: 1000
#
#  time_limit: 0.01
#
#model:
#  latent_reg_wt: 4
#  _type: wpp

#  lr: 2.e-3
#  norm_type: None
#  residual: True

#
##  gan_wt: 1
#
##  gan_warm_start: 3
#
##  latent_reg_wt: 100
#
#  scheduler_type: '_x_'
##  scheduler_decay: .5
##  scheduler_patience: 4
##  scheduler_cooldown: 2
##  scheduler_step: 10

#  squeeze: True
##  internal_channels: [256, 256, 256, 512, 512]
#  internal_channels: [256, 256, 256, 512, 512, 1024]
#
#  generator:
#
##    internal_channels: [512, 512, 256, 256, 256]
#    internal_channels: [1024, 512, 512, 256, 256, 256]

#  encoder:
#    scheduler_type: 'plateau'
#
#
##  latent_reg_wt: 2
#
##  norm_type: None
#
#
#
#
##  gen_types: ['gen']
#
##  rec_noise: 0.2
#
##  gan_wt: 1
#
##  gen_types: ['gen']
#
##dataset.kwargs.download = true
#
##resume = 'test-pycharm_191121-154737'
##
##extend = 7