parents: ['basics']

name: 'vae'

model:
    _type: 'wpp-vae'

    gan_wt: 0

    latent_reg_wt: 1

    encoder:
#        _type: 'normal-conv'
        _mod: 'normal'

#optim:
#  lr: 2.e-4
#  beta1: 0.9
#  beta2: 0.999